// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.3
// source: courses-microservice.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for getting a course.
type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_courses_microservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetCourseRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

// Response message for getting a course.
type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_courses_microservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

// Request message for creating a new course.
type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Course        *Course                `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_courses_microservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateCourseRequest) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

// Response message for creating a new course.
type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_courses_microservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{3}
}

// Request message for updating a course.
type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Course        *Course                `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_courses_microservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCourseRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateCourseRequest) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

// Response message for updating a course.
type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_courses_microservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{5}
}

// Request message for deleting a course.
type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_courses_microservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCourseRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

// Response message for deleting a course.
type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_courses_microservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{7}
}

// Request message for adding a student to a course.
type AddStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=studentId,proto3" json:"studentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStudentRequest) Reset() {
	*x = AddStudentRequest{}
	mi := &file_courses_microservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStudentRequest) ProtoMessage() {}

func (x *AddStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStudentRequest.ProtoReflect.Descriptor instead.
func (*AddStudentRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{8}
}

func (x *AddStudentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddStudentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AddStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// Response message for adding a student to a course.
type AddStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStudentResponse) Reset() {
	*x = AddStudentResponse{}
	mi := &file_courses_microservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStudentResponse) ProtoMessage() {}

func (x *AddStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStudentResponse.ProtoReflect.Descriptor instead.
func (*AddStudentResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{9}
}

// Request message for removing a student from a course.
type RemoveStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=studentId,proto3" json:"studentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStudentRequest) Reset() {
	*x = RemoveStudentRequest{}
	mi := &file_courses_microservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStudentRequest) ProtoMessage() {}

func (x *RemoveStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStudentRequest.ProtoReflect.Descriptor instead.
func (*RemoveStudentRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveStudentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RemoveStudentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *RemoveStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// Response message for removing a student from a course.
type RemoveStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStudentResponse) Reset() {
	*x = RemoveStudentResponse{}
	mi := &file_courses_microservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStudentResponse) ProtoMessage() {}

func (x *RemoveStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStudentResponse.ProtoReflect.Descriptor instead.
func (*RemoveStudentResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{11}
}

// Request message for adding a staff member to a course.
type AddStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	StaffId       string                 `protobuf:"bytes,3,opt,name=staffId,proto3" json:"staffId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStaffRequest) Reset() {
	*x = AddStaffRequest{}
	mi := &file_courses_microservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffRequest) ProtoMessage() {}

func (x *AddStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffRequest.ProtoReflect.Descriptor instead.
func (*AddStaffRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{12}
}

func (x *AddStaffRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddStaffRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AddStaffRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

// Response message for adding a staff member to a course.
type AddStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStaffResponse) Reset() {
	*x = AddStaffResponse{}
	mi := &file_courses_microservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffResponse) ProtoMessage() {}

func (x *AddStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffResponse.ProtoReflect.Descriptor instead.
func (*AddStaffResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{13}
}

// Request message for removing a staff member from a course.
type RemoveStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	StaffId       string                 `protobuf:"bytes,3,opt,name=staffId,proto3" json:"staffId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStaffRequest) Reset() {
	*x = RemoveStaffRequest{}
	mi := &file_courses_microservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStaffRequest) ProtoMessage() {}

func (x *RemoveStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStaffRequest.ProtoReflect.Descriptor instead.
func (*RemoveStaffRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveStaffRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RemoveStaffRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *RemoveStaffRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

// Response message for removing a staff member from a course.
type RemoveStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStaffResponse) Reset() {
	*x = RemoveStaffResponse{}
	mi := &file_courses_microservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStaffResponse) ProtoMessage() {}

func (x *RemoveStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStaffResponse.ProtoReflect.Descriptor instead.
func (*RemoveStaffResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{15}
}

// Request message for getting all students in a course.
type GetCourseStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseStudentsRequest) Reset() {
	*x = GetCourseStudentsRequest{}
	mi := &file_courses_microservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseStudentsRequest) ProtoMessage() {}

func (x *GetCourseStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseStudentsRequest.ProtoReflect.Descriptor instead.
func (*GetCourseStudentsRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{16}
}

func (x *GetCourseStudentsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetCourseStudentsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

// Response message for getting all students in a course.
type GetCourseStudentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentIds    []string               `protobuf:"bytes,1,rep,name=studentIds,proto3" json:"studentIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseStudentsResponse) Reset() {
	*x = GetCourseStudentsResponse{}
	mi := &file_courses_microservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseStudentsResponse) ProtoMessage() {}

func (x *GetCourseStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseStudentsResponse.ProtoReflect.Descriptor instead.
func (*GetCourseStudentsResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{17}
}

func (x *GetCourseStudentsResponse) GetStudentIds() []string {
	if x != nil {
		return x.StudentIds
	}
	return nil
}

// Request message for getting all staff members in a course.
type GetCourseStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseStaffRequest) Reset() {
	*x = GetCourseStaffRequest{}
	mi := &file_courses_microservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseStaffRequest) ProtoMessage() {}

func (x *GetCourseStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseStaffRequest.ProtoReflect.Descriptor instead.
func (*GetCourseStaffRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{18}
}

func (x *GetCourseStaffRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetCourseStaffRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

// Response message for getting all staff members in a course.
type GetCourseStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffIds      []string               `protobuf:"bytes,1,rep,name=staffIds,proto3" json:"staffIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseStaffResponse) Reset() {
	*x = GetCourseStaffResponse{}
	mi := &file_courses_microservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseStaffResponse) ProtoMessage() {}

func (x *GetCourseStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseStaffResponse.ProtoReflect.Descriptor instead.
func (*GetCourseStaffResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{19}
}

func (x *GetCourseStaffResponse) GetStaffIds() []string {
	if x != nil {
		return x.StaffIds
	}
	return nil
}

// Request message for getting a student's courses.
type GetStudentCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=studentId,proto3" json:"studentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentCoursesRequest) Reset() {
	*x = GetStudentCoursesRequest{}
	mi := &file_courses_microservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentCoursesRequest) ProtoMessage() {}

func (x *GetStudentCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetStudentCoursesRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{20}
}

func (x *GetStudentCoursesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetStudentCoursesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// Response message for getting a student's courses.
type GetStudentCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoursesIds    []string               `protobuf:"bytes,1,rep,name=coursesIds,proto3" json:"coursesIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentCoursesResponse) Reset() {
	*x = GetStudentCoursesResponse{}
	mi := &file_courses_microservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentCoursesResponse) ProtoMessage() {}

func (x *GetStudentCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetStudentCoursesResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{21}
}

func (x *GetStudentCoursesResponse) GetCoursesIds() []string {
	if x != nil {
		return x.CoursesIds
	}
	return nil
}

// Request message for getting a staff's courses.
type GetStaffCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StaffId       string                 `protobuf:"bytes,2,opt,name=staffId,proto3" json:"staffId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffCoursesRequest) Reset() {
	*x = GetStaffCoursesRequest{}
	mi := &file_courses_microservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffCoursesRequest) ProtoMessage() {}

func (x *GetStaffCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetStaffCoursesRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{22}
}

func (x *GetStaffCoursesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetStaffCoursesRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

// Response message for getting a staff's courses.
type GetStaffCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoursesIds    []string               `protobuf:"bytes,1,rep,name=coursesIds,proto3" json:"coursesIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffCoursesResponse) Reset() {
	*x = GetStaffCoursesResponse{}
	mi := &file_courses_microservice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffCoursesResponse) ProtoMessage() {}

func (x *GetStaffCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetStaffCoursesResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{23}
}

func (x *GetStaffCoursesResponse) GetCoursesIds() []string {
	if x != nil {
		return x.CoursesIds
	}
	return nil
}

// Request message for adding an announcement to a course.
type AddAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Announcement  string                 `protobuf:"bytes,3,opt,name=announcement,proto3" json:"announcement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAnnouncementRequest) Reset() {
	*x = AddAnnouncementRequest{}
	mi := &file_courses_microservice_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAnnouncementRequest) ProtoMessage() {}

func (x *AddAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*AddAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{24}
}

func (x *AddAnnouncementRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddAnnouncementRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AddAnnouncementRequest) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

// Response message for adding an announcement to a course.
type AddAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAnnouncementResponse) Reset() {
	*x = AddAnnouncementResponse{}
	mi := &file_courses_microservice_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAnnouncementResponse) ProtoMessage() {}

func (x *AddAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*AddAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{25}
}

// Request message for removing an announcement from a course.
type RemoveAnnouncementRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId       string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	AnnouncementId string                 `protobuf:"bytes,3,opt,name=announcementId,proto3" json:"announcementId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveAnnouncementRequest) Reset() {
	*x = RemoveAnnouncementRequest{}
	mi := &file_courses_microservice_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAnnouncementRequest) ProtoMessage() {}

func (x *RemoveAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*RemoveAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveAnnouncementRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RemoveAnnouncementRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *RemoveAnnouncementRequest) GetAnnouncementId() string {
	if x != nil {
		return x.AnnouncementId
	}
	return ""
}

// Response message for removing an announcement from a course.
type RemoveAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAnnouncementResponse) Reset() {
	*x = RemoveAnnouncementResponse{}
	mi := &file_courses_microservice_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAnnouncementResponse) ProtoMessage() {}

func (x *RemoveAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*RemoveAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{27}
}

// Request message for updating an announcement in a course.
type UpdateAnnouncementRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Token               string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId            string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	AnnouncementId      string                 `protobuf:"bytes,3,opt,name=announcementId,proto3" json:"announcementId,omitempty"`
	UpdatedAnnouncement string                 `protobuf:"bytes,4,opt,name=updatedAnnouncement,proto3" json:"updatedAnnouncement,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateAnnouncementRequest) Reset() {
	*x = UpdateAnnouncementRequest{}
	mi := &file_courses_microservice_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementRequest) ProtoMessage() {}

func (x *UpdateAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateAnnouncementRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateAnnouncementRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateAnnouncementRequest) GetAnnouncementId() string {
	if x != nil {
		return x.AnnouncementId
	}
	return ""
}

func (x *UpdateAnnouncementRequest) GetUpdatedAnnouncement() string {
	if x != nil {
		return x.UpdatedAnnouncement
	}
	return ""
}

// Response message for updating an announcement in a course.
type UpdateAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnouncementResponse) Reset() {
	*x = UpdateAnnouncementResponse{}
	mi := &file_courses_microservice_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementResponse) ProtoMessage() {}

func (x *UpdateAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{29}
}

// Request message for uploading course material.
type UploadCourseMaterialRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId       string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	CourseMaterial string                 `protobuf:"bytes,3,opt,name=courseMaterial,proto3" json:"courseMaterial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadCourseMaterialRequest) Reset() {
	*x = UploadCourseMaterialRequest{}
	mi := &file_courses_microservice_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCourseMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCourseMaterialRequest) ProtoMessage() {}

func (x *UploadCourseMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCourseMaterialRequest.ProtoReflect.Descriptor instead.
func (*UploadCourseMaterialRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{30}
}

func (x *UploadCourseMaterialRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UploadCourseMaterialRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UploadCourseMaterialRequest) GetCourseMaterial() string {
	if x != nil {
		return x.CourseMaterial
	}
	return ""
}

// Response message for uploading course material.
type UploadCourseMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCourseMaterialResponse) Reset() {
	*x = UploadCourseMaterialResponse{}
	mi := &file_courses_microservice_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCourseMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCourseMaterialResponse) ProtoMessage() {}

func (x *UploadCourseMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCourseMaterialResponse.ProtoReflect.Descriptor instead.
func (*UploadCourseMaterialResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{31}
}

// Request message for getting course material.
type GetCourseMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseMaterialRequest) Reset() {
	*x = GetCourseMaterialRequest{}
	mi := &file_courses_microservice_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseMaterialRequest) ProtoMessage() {}

func (x *GetCourseMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseMaterialRequest.ProtoReflect.Descriptor instead.
func (*GetCourseMaterialRequest) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{32}
}

func (x *GetCourseMaterialRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetCourseMaterialRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

// Response message for getting course material.
type GetCourseMaterialResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CourseMaterial string                 `protobuf:"bytes,1,opt,name=courseMaterial,proto3" json:"courseMaterial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCourseMaterialResponse) Reset() {
	*x = GetCourseMaterialResponse{}
	mi := &file_courses_microservice_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseMaterialResponse) ProtoMessage() {}

func (x *GetCourseMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseMaterialResponse.ProtoReflect.Descriptor instead.
func (*GetCourseMaterialResponse) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{33}
}

func (x *GetCourseMaterialResponse) GetCourseMaterial() string {
	if x != nil {
		return x.CourseMaterial
	}
	return ""
}

// Message representing a course.
type Course struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CourseId       string                 `protobuf:"bytes,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	CourseName     string                 `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	Semester       string                 `protobuf:"bytes,3,opt,name=semester,proto3" json:"semester,omitempty"`
	CourseMaterial string                 `protobuf:"bytes,4,opt,name=courseMaterial,proto3" json:"courseMaterial,omitempty"` // out of scope for now
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Announcements  []string               `protobuf:"bytes,6,rep,name=announcements,proto3" json:"announcements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_courses_microservice_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_courses_microservice_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_courses_microservice_proto_rawDescGZIP(), []int{34}
}

func (x *Course) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Course) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *Course) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *Course) GetCourseMaterial() string {
	if x != nil {
		return x.CourseMaterial
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetAnnouncements() []string {
	if x != nil {
		return x.Announcements
	}
	return nil
}

var File_courses_microservice_proto protoreflect.FileDescriptor

var file_courses_microservice_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x22,
	0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x22, 0x16, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x16,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x63, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x41,
	0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x66, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x5d, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49,
	0x64, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0x49, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x73, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x49, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49,
	0x64, 0x22, 0x39, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x49, 0x64, 0x73, 0x22, 0x6e, 0x0a, 0x16,
	0x41, 0x64, 0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x19, 0x0a, 0x17,
	0x41, 0x64, 0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x75, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x1c,
	0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa7, 0x01, 0x0a,
	0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e,
	0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x77, 0x0a, 0x1b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x1e, 0x0a,
	0x1c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x22, 0xd0, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x32, 0xd1, 0x0b, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4d, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54,
	0x6f, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x58, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54, 0x6f, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x18,
	0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x1b, 0x2e, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x6f, 0x6d,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x22, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x65, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x22, 0x2e,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x14, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x24,
	0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x12, 0x21, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x65, 0x74, 0x74, 0x65, 0x72, 0x47, 0x52, 0x2f, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_courses_microservice_proto_rawDescOnce sync.Once
	file_courses_microservice_proto_rawDescData = file_courses_microservice_proto_rawDesc
)

func file_courses_microservice_proto_rawDescGZIP() []byte {
	file_courses_microservice_proto_rawDescOnce.Do(func() {
		file_courses_microservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_courses_microservice_proto_rawDescData)
	})
	return file_courses_microservice_proto_rawDescData
}

var file_courses_microservice_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_courses_microservice_proto_goTypes = []any{
	(*GetCourseRequest)(nil),             // 0: courses.GetCourseRequest
	(*GetCourseResponse)(nil),            // 1: courses.GetCourseResponse
	(*CreateCourseRequest)(nil),          // 2: courses.CreateCourseRequest
	(*CreateCourseResponse)(nil),         // 3: courses.CreateCourseResponse
	(*UpdateCourseRequest)(nil),          // 4: courses.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),         // 5: courses.UpdateCourseResponse
	(*DeleteCourseRequest)(nil),          // 6: courses.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),         // 7: courses.DeleteCourseResponse
	(*AddStudentRequest)(nil),            // 8: courses.AddStudentRequest
	(*AddStudentResponse)(nil),           // 9: courses.AddStudentResponse
	(*RemoveStudentRequest)(nil),         // 10: courses.RemoveStudentRequest
	(*RemoveStudentResponse)(nil),        // 11: courses.RemoveStudentResponse
	(*AddStaffRequest)(nil),              // 12: courses.AddStaffRequest
	(*AddStaffResponse)(nil),             // 13: courses.AddStaffResponse
	(*RemoveStaffRequest)(nil),           // 14: courses.RemoveStaffRequest
	(*RemoveStaffResponse)(nil),          // 15: courses.RemoveStaffResponse
	(*GetCourseStudentsRequest)(nil),     // 16: courses.GetCourseStudentsRequest
	(*GetCourseStudentsResponse)(nil),    // 17: courses.GetCourseStudentsResponse
	(*GetCourseStaffRequest)(nil),        // 18: courses.GetCourseStaffRequest
	(*GetCourseStaffResponse)(nil),       // 19: courses.GetCourseStaffResponse
	(*GetStudentCoursesRequest)(nil),     // 20: courses.GetStudentCoursesRequest
	(*GetStudentCoursesResponse)(nil),    // 21: courses.GetStudentCoursesResponse
	(*GetStaffCoursesRequest)(nil),       // 22: courses.GetStaffCoursesRequest
	(*GetStaffCoursesResponse)(nil),      // 23: courses.GetStaffCoursesResponse
	(*AddAnnouncementRequest)(nil),       // 24: courses.AddAnnouncementRequest
	(*AddAnnouncementResponse)(nil),      // 25: courses.AddAnnouncementResponse
	(*RemoveAnnouncementRequest)(nil),    // 26: courses.RemoveAnnouncementRequest
	(*RemoveAnnouncementResponse)(nil),   // 27: courses.RemoveAnnouncementResponse
	(*UpdateAnnouncementRequest)(nil),    // 28: courses.UpdateAnnouncementRequest
	(*UpdateAnnouncementResponse)(nil),   // 29: courses.UpdateAnnouncementResponse
	(*UploadCourseMaterialRequest)(nil),  // 30: courses.UploadCourseMaterialRequest
	(*UploadCourseMaterialResponse)(nil), // 31: courses.UploadCourseMaterialResponse
	(*GetCourseMaterialRequest)(nil),     // 32: courses.GetCourseMaterialRequest
	(*GetCourseMaterialResponse)(nil),    // 33: courses.GetCourseMaterialResponse
	(*Course)(nil),                       // 34: courses.Course
}
var file_courses_microservice_proto_depIdxs = []int32{
	34, // 0: courses.GetCourseResponse.course:type_name -> courses.Course
	34, // 1: courses.CreateCourseRequest.course:type_name -> courses.Course
	34, // 2: courses.UpdateCourseRequest.course:type_name -> courses.Course
	0,  // 3: courses.CoursesService.GetCourse:input_type -> courses.GetCourseRequest
	2,  // 4: courses.CoursesService.CreateCourse:input_type -> courses.CreateCourseRequest
	4,  // 5: courses.CoursesService.UpdateCourse:input_type -> courses.UpdateCourseRequest
	6,  // 6: courses.CoursesService.DeleteCourse:input_type -> courses.DeleteCourseRequest
	8,  // 7: courses.CoursesService.AddStudentToCourse:input_type -> courses.AddStudentRequest
	10, // 8: courses.CoursesService.RemoveStudentFromCourse:input_type -> courses.RemoveStudentRequest
	12, // 9: courses.CoursesService.AddStaffToCourse:input_type -> courses.AddStaffRequest
	14, // 10: courses.CoursesService.RemoveStaffFromCourse:input_type -> courses.RemoveStaffRequest
	16, // 11: courses.CoursesService.GetCourseStudents:input_type -> courses.GetCourseStudentsRequest
	18, // 12: courses.CoursesService.GetCourseStaff:input_type -> courses.GetCourseStaffRequest
	20, // 13: courses.CoursesService.GetStudentCourses:input_type -> courses.GetStudentCoursesRequest
	22, // 14: courses.CoursesService.GetStaffCourses:input_type -> courses.GetStaffCoursesRequest
	24, // 15: courses.CoursesService.AddAnnouncementToCourse:input_type -> courses.AddAnnouncementRequest
	26, // 16: courses.CoursesService.RemoveAnnouncementFromCourse:input_type -> courses.RemoveAnnouncementRequest
	28, // 17: courses.CoursesService.UpdateAnnouncementInCourse:input_type -> courses.UpdateAnnouncementRequest
	30, // 18: courses.CoursesService.UploadCourseMaterial:input_type -> courses.UploadCourseMaterialRequest
	32, // 19: courses.CoursesService.GetCourseMaterial:input_type -> courses.GetCourseMaterialRequest
	1,  // 20: courses.CoursesService.GetCourse:output_type -> courses.GetCourseResponse
	3,  // 21: courses.CoursesService.CreateCourse:output_type -> courses.CreateCourseResponse
	5,  // 22: courses.CoursesService.UpdateCourse:output_type -> courses.UpdateCourseResponse
	7,  // 23: courses.CoursesService.DeleteCourse:output_type -> courses.DeleteCourseResponse
	9,  // 24: courses.CoursesService.AddStudentToCourse:output_type -> courses.AddStudentResponse
	11, // 25: courses.CoursesService.RemoveStudentFromCourse:output_type -> courses.RemoveStudentResponse
	13, // 26: courses.CoursesService.AddStaffToCourse:output_type -> courses.AddStaffResponse
	15, // 27: courses.CoursesService.RemoveStaffFromCourse:output_type -> courses.RemoveStaffResponse
	17, // 28: courses.CoursesService.GetCourseStudents:output_type -> courses.GetCourseStudentsResponse
	19, // 29: courses.CoursesService.GetCourseStaff:output_type -> courses.GetCourseStaffResponse
	21, // 30: courses.CoursesService.GetStudentCourses:output_type -> courses.GetStudentCoursesResponse
	23, // 31: courses.CoursesService.GetStaffCourses:output_type -> courses.GetStaffCoursesResponse
	25, // 32: courses.CoursesService.AddAnnouncementToCourse:output_type -> courses.AddAnnouncementResponse
	27, // 33: courses.CoursesService.RemoveAnnouncementFromCourse:output_type -> courses.RemoveAnnouncementResponse
	29, // 34: courses.CoursesService.UpdateAnnouncementInCourse:output_type -> courses.UpdateAnnouncementResponse
	31, // 35: courses.CoursesService.UploadCourseMaterial:output_type -> courses.UploadCourseMaterialResponse
	33, // 36: courses.CoursesService.GetCourseMaterial:output_type -> courses.GetCourseMaterialResponse
	20, // [20:37] is the sub-list for method output_type
	3,  // [3:20] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_courses_microservice_proto_init() }
func file_courses_microservice_proto_init() {
	if File_courses_microservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_courses_microservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_courses_microservice_proto_goTypes,
		DependencyIndexes: file_courses_microservice_proto_depIdxs,
		MessageInfos:      file_courses_microservice_proto_msgTypes,
	}.Build()
	File_courses_microservice_proto = out.File
	file_courses_microservice_proto_rawDesc = nil
	file_courses_microservice_proto_goTypes = nil
	file_courses_microservice_proto_depIdxs = nil
}
